# Generated by Django 6.0.5 on 2026-07-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatconversation_force_agent_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='force_agent_auto',
        ),
    ]
