# Generated by Django 6.0.5 on 2026-08-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_attachments_read_state_push_unique_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='context_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='last_page_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='page_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
