# Generated by Django 6.0.5 on 2026-06-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add_product', 'إضافة منتج جديد'), ('update_product_price', 'تعديل سعر منتج'), ('mark_unavailable', 'تعطيل توفر منتج'), ('other', 'أخرى')], max_length=30)),
                ('payload', models.JSONField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_globally_active', models.BooleanField(default=True)),
                ('auto_reply_mode', models.CharField(choices=[('full_auto', 'رد تلقائي كامل'), ('suggest_only', 'اقتراح فقط'), ('off', 'إيقاف تام')], default='suggest_only', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
