# Generated by Django 6.0.5 on 2026-07-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agentsettings_auto_reply_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='fb_followers_override',
            field=models.IntegerField(default=1250),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='fb_page_id',
            field=models.CharField(default='61591261844925', max_length=100),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='fb_page_url',
            field=models.URLField(default='https://www.facebook.com/profile.php?id=61591261844925', max_length=500),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='fb_reach_override',
            field=models.IntegerField(default=4800),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='ig_followers_override',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='ig_page_url',
            field=models.URLField(default='https://instagram.com/dummy', max_length=500),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='is_google_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='is_meta_connected',
            field=models.BooleanField(default=True),
        ),
    ]
