# Generated by Django 6.0.5 on 2026-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentsettings_fb_followers_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPostCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('caption', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='last_meta_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='meta_access_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
