# Generated by Django 6.0.5 on 2026-07-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_metapostcache_agentsettings_last_meta_sync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('session_key', models.CharField(blank=True, default='', max_length=100)),
                ('referrer_type', models.CharField(choices=[('direct', 'Direct'), ('social', 'Social'), ('organic', 'Organic'), ('referral', 'Referral')], default='direct', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='agent_webpa_path_08bf3b_idx'), models.Index(fields=['referrer_type'], name='agent_webpa_referre_09fc14_idx')],
            },
        ),
    ]
