# Generated by Django 6.0.5 on 2026-07-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_webpagevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GADailyTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sessions', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_session_duration_seconds', models.FloatField(default=0.0)),
                ('conversions', models.IntegerField(default=0)),
                ('source_organic', models.IntegerField(default=0)),
                ('source_social', models.IntegerField(default=0)),
                ('source_direct', models.IntegerField(default=0)),
                ('source_referral', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='ga4_property_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='ga4_service_account_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='is_ga4_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='last_ga4_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('ga4', 'Google Analytics'), ('site', 'Internal WebPageVisit')], max_length=20)),
                ('metric_name', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'metric_name', 'date'], name='agent_daily_source_80cb4f_idx')],
                'unique_together': {('date', 'source', 'metric_name')},
            },
        ),
        migrations.CreateModel(
            name='FacebookPostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('message', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('permalink_url', models.URLField(blank=True, default='', max_length=500)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('reach', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('video_views', models.IntegerField(default=0)),
                ('post_type', models.CharField(default='status', max_length=20)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['published_at'], name='agent_faceb_publish_1a7c90_idx')],
            },
        ),
        migrations.CreateModel(
            name='GACampaignSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('utm_campaign', models.CharField(db_index=True, max_length=150)),
                ('sessions', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('engaged_sessions', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'utm_campaign')},
            },
        ),
        migrations.CreateModel(
            name='GATopPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page_path', models.CharField(max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_duration_seconds', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('date', 'page_path')},
            },
        ),
    ]
