# Generated by Codex on 2026-07-24

from django.db import migrations, models


def clear_seeded_settings(apps, schema_editor):
    AgentSettings = apps.get_model("agent", "AgentSettings")
    FacebookPostMetric = apps.get_model("agent", "FacebookPostMetric")
    MetaPostCache = apps.get_model("agent", "MetaPostCache")
    seeded_fb_url = "https://www.facebook.com/profile.php?id=61591261844925"
    seeded_ig_url = "https://instagram.com/dummy"

    FacebookPostMetric.objects.filter(post_id__startswith="fb_post_").delete()
    MetaPostCache.objects.filter(post_id__startswith="fb_post_").delete()

    for settings in AgentSettings.objects.all():
        changed = []
        if settings.fb_page_url == seeded_fb_url:
            settings.fb_page_url = ""
            changed.append("fb_page_url")
        if settings.fb_page_id == "61591261844925":
            settings.fb_page_id = ""
            changed.append("fb_page_id")
        if settings.fb_followers_override in (1250, 12500):
            settings.fb_followers_override = None
            changed.append("fb_followers_override")
        if settings.fb_reach_override in (4800, 45800):
            settings.fb_reach_override = None
            changed.append("fb_reach_override")
        if settings.ig_page_url == seeded_ig_url:
            settings.ig_page_url = ""
            changed.append("ig_page_url")
        if settings.ig_followers_override in (0, 8400):
            settings.ig_followers_override = None
            changed.append("ig_followers_override")
        if settings.is_meta_connected and not settings.meta_access_token:
            settings.is_meta_connected = False
            changed.append("is_meta_connected")
        if changed:
            settings.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0006_gadailytraffic_agentsettings_ga4_property_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentsettings",
            name="fb_followers_override",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="agentsettings",
            name="fb_page_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="agentsettings",
            name="fb_page_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="agentsettings",
            name="fb_reach_override",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="agentsettings",
            name="ig_followers_override",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="agentsettings",
            name="ig_page_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="agentsettings",
            name="is_meta_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(clear_seeded_settings, migrations.RunPython.noop),
    ]
