# Generated by Django 6.0.5 on 2026-06-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_order', 'أوردر جديد'), ('new_chat_message', 'رسالة شات جديدة'), ('agent_action_request', 'طلب موافقة من الإيجنت')], max_length=30)),
                ('related_object_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_via_telegram', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
