# Generated by Django 6.0.5 on 2026-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deposit_note',
            field=models.CharField(blank=True, help_text='ملاحظة عن الديبوزيت، مثلاً: يتم دفعه عند التأكيد', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
