# Generated by Django 5.1 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_searchquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='ألوان قابلة للاختيار، مثال: ["أوف وايت", "رمادي"]',
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="measurement_image",
            field=models.ImageField(
                blank=True,
                help_text="صورة اختيارية توضح مقاسات المنتج أو حجمه داخل مساحة حقيقية.",
                null=True,
                upload_to="product_measurements/",
            ),
        ),
    ]
