# Generated by Django 6.0.5 on 2026-07-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_shipping_location_orderitem_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_proofs/'),
        ),
    ]
