# Generated by Django 5.1 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_storepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="selected_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
